
=head1 Unique


Unique id    

PhilipRBrenan@yahoo.com, 2004, Perl license


=head2 Synopsis


#example t/unique.t


=head2 Description


Returns a unique id each time it is called.

 
 package unique;
 use Carp;
 


=head2 Constructors



=head3 unique


Return new unique id

 
 my $unique = 0;
 
 sub unique() {++$unique}
 


=head3 new


Return new unique id, synonym for L</unique>

 
 sub new {unique()}
 


=head2 Exports


Export L</unique>

 
 use exports qw(
   unique ()
  );
 
 #_ Unique _____________________________________________________________
 # Package loaded successfully
 #______________________________________________________________________
 
 1;
